# Generated by Django 6.0.3 on 2026-05-28 14:26

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, verbose_name='Необходимое оборудование (список)')),
                ('reservation_period', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Время резервирования')),
            ],
        ),
    ]
